### ISSUE TITLE
CSVs on GitHub

### ISSUE THREAD

**Issue by mfansler** [chilampoon/ANGSD-project#1]
Note that were this file renamed to `.csv`, it would show up with nice rendering on GitHub ([see Docs](https://docs.github.com/en/github/managing-files-in-a-repository/rendering-csv-and-tsv-data)).

https://github.com/chilampoon/ANGSD-project/blob/0aec8d1937cbf63c2b8a508a132d2d6ebbf31e02/data/SraRunTable.txt

**Comment by chilampoon** [comment]
Done!

**Comment by mfansler** [comment]
Nice!
